---
- hosts: mysql
  become: true
  vars:
    mysql_root_password: 10203040
  tasks:
    - name: install the mySQL packages
      apt:
        pkg: '{{ item }}'
        state: present
        update_cache: yes
      with_items:
        - mysql-client
        - libmysqlclient-dev
        - mysql-server
        - python-mysqldb
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Start the MySQL service
      service:
        name: mysql
        state: started

    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: '{{ item }}'
        password: '{{ mysql_root_password }}'
      with_items:
        - ‘{{ ansible_eth0.ipv4.address }}’
        - localhost

    - name: copy .my.cnf file with root password credentials
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600

    - name: Add user to the database
      mysql_user:
        name: '{{ ansible_user }}'
        password: '12345'
        host: '{{ item }}'
        priv: '*.*:ALL,GRANT '
        state: present
      with_items:
        - localhost
        - '%'
