---
- name: create /var/www/ directory
  file: 
    dest: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- block:
  - name: Clone git repository
    git:
      dest: /var/www/laravel
      repo: https://github.com/JeffreyWay/Laravel-From-Scratch-Blog-Project.git
      update: no
    register: repo 

  - name: set .env file
    template:
      src: env.j2
      dest: /var/www/laravel/.env

  - name: set database.php conf file
    copy:
      src: database.php
      dest: /var/www/laravel/config/database.php
      mode: u+rw,g-rw,o-r

  - name: php migrate and seed
    shell:
      cmd: composer update
      chdir: /var/www/laravel

  - name: php migrate and seed
    shell:
      cmd: composer install
      chdir: /var/www/laravel

  - name: php migrate and seed
    shell:
      cmd: php artisan {{ item }}
      chdir: /var/www/laravel
    with_items:
      - migrate --seed --force
      - config:clear
      - key:generate --force
  become: true
  become_user: www-data
  notify:
      - restart php8.1-fpm
      - restart nginx