---
- name: create /var/www/ directory
  file: 
    dest: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- block:
  - name: Clone git repository
    git:
      dest: /var/www/laravel
      repo: https://github.com/savanihd/Laravel-9-CRUD.git
      update: no
    register: repo 

  - name: set .env file
    template:
      src: env.j2
      dest: /var/www/laravel/.env

  - name: set database.php conf file
    copy:
      src: database.php
      dest: /var/www/laravel/config/database.php
      mode: u+rw,g-rw,o-r
  become: true
  become_user: www-data

- block:
  - name: composer install
    community.general.composer:
      command: install
      working_dir: /var/www/laravel
 
  - name: php migrate and seed
    shell:
      cmd: php artisan migrate --seed --force
      chdir: /var/www/laravel

  - name: clear the config
    shell:
      cmd: php artisan config:clear
      chdir: /var/www/laravel

  - name: php migrate and seed
    shell:
      cmd: php artisan key:generate --force
      chdir: /var/www/laravel
  when: repo.changed
  notify:
    - restart php8.1-fpm
    - restart nginx