---
# handlers file for laravel_role
- name: restart php8.1-fpm
  sysvinit: 
    name: php8.1-fpm
    state: "{{ item }}"
  with_items:
    - stopped
    - started

- name: restart nginx
  sysvinit:
    name: nginx
    state: restarted