---
- name: create /var/www/ directory
  ansible.builtin.file:
    dest: /var/www/
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- name: Clone git repository
  ansible.builtin.git:
    dest: /var/www/laravel
    repo: https://github.com/JeffreyWay/Laravel-From-Scratch-Blog-Project.git
    update: no
  register: repo
  become: true
  become_user: www-data

- name: Configure the site then migrate and seed the database
  block:
  - name: set .env file
    ansible.builtin.template:
      src: env.j2
      dest: /var/www/laravel/.env

  - name: set database.php conf file
    ansible.builtin.copy:
      src: database.php
      dest: /var/www/laravel/config/database.php
      mode: u+rw,g-rw,o-r

  - name: Composer update
    ansible.builtin.shell:
      cmd: composer update
      chdir: /var/www/laravel

  - name: composer install
    ansible.builtin.shell:
      cmd: composer install
      chdir: /var/www/laravel

  - name: php artisan steps
    ansible.builtin.shell:
      cmd: php artisan {{ item }}
      chdir: /var/www/laravel
    with_items:
      - migrate --seed --force
      - storage:link
      - config:clear
      - key:generate --force
  become: true
  become_user: www-data
  notify:
      - restart php8.1-fpm
      - restart nginx
  when: repo is changed