- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install php and related packages
  ansible.builtin.apt:
    name: "{{ php_pkgs }}"
    state: present

- name: Checks if Composer is already installed
  ansible.builtin.command: "{{ composer_path }}"
  ignore_errors: true
  register: composer_installed
  changed_when: false

- name: Install Composer if its not already installed
  block:

    - name: Download Composer Installation Script (if not already installed)
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Run Composer Installer (if not already installed)
      ansible.builtin.command:
        cmd: /usr/bin/php /tmp/composer-setup.php
        creates: composer.phar

    - name: Copy Composer Executable to /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: composer.phar
        dest: /usr/local/bin/composer
        remote_src: yes
        mode: '0755'

    - name: Remove phar
      ansible.builtin.file:
        path: composer.phar
        state: absent

    - name: Remove Install Script
      ansible.builtin.file:
        path: /tmp/composer-setup.php
        state: absent
  when: composer_installed is failed