---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: molecule/requirements.yml
    requirements-file: molecule/collections.yml
driver:
  name: docker
platforms:
  - name: site
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    published_ports:
      - 0.0.0.0:8080:80/tcp
    networks:
      - name: "laravel"
  - name: mysql
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    published_ports:
      - 0.0.0.0:3306:3306/tcp
    networks:
      - name: "laravel"
provisioner:
  name: ansible
  env:
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: blog
    DB_USERNAME: molecule
    DB_PASSWORD: moleculepass
    APP_ENV: local
    APP_DEBUG: true
verifier:
  name: testinfra